services:
  postgres:
    image: postgres:18
    container_name: discord_like_db
    environment:
      POSTGRES_USER: vincent
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: discord_like
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
